import './globals.css'
import { Inter } from 'next/font/google'
import Container from '@/components/Container'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1"
        />
      </head>
      <body className={inter.className}>
      <div>
      <Navbar />
      <main className="pt-navigation-height">
      {children}
      </main>
      <Container><footer>footer</footer></Container>
        </div>
      </body>
    </html>
  )
}
